# Default values for flair-notifications.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flair-notifications
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8091

env:
  APP_CONFIG: /flair-config/application-kube.yml
  NODE_ENV: kube
  SLEEP_TIME: 60
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  GRPC_SSL_ENABLED: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
