{{- if .Values.ingress.enabled -}}
{{- $fullName := include "flair-bi.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "flair-bi.name" . }}
    helm.sh/chart: {{ include "flair-bi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: http
{{- end }}
