apiVersion: v1
kind: Service
metadata:
  name: {{ include "flair-registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flair-registry.name" . }}
    helm.sh/chart: {{ include "flair-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.eurekaPort }}
      targetPort: eureka
      protocol: TCP
      name: eureka
    - port: {{ .Values.service.configPort }}
      targetPort: config
      protocol: TCP
      name: config
  selector:
    app.kubernetes.io/name: {{ include "flair-registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
