# Default values for flair-cache.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flair-cache
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6565

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: kube
  CONFIG_URI: http://flair-registry:8761
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  GRPC_SSL_ENABLED: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

annotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"
