# Default values for flair-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flair-engine
  tag: v2.2.5-SNAPSHOT.c873a96
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# secretName: flair-engine-secret

service:
  type: ClusterIP
  port: 6565

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: grpc,kube
  CONFIG_URI: http://flair-registry:8761
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  POSTGRES_URI: flair-engine-pg-postgresql:5432
  GRPC_SSL_ENABLED: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

annotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"
