# Default values for flair-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: flairbi/flair-engine
  tag: v1.1.13
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6565

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: grpc,kube
  CONFIG_URI: http://flair-registry:8761
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  POSTGRES_URI: flair-engine-pg-postgresql:5432
  GRPC_SSL_ENABLED: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
