apiVersion: v1
kind: Pod
metadata:
  name: flair-data-generator
spec:
  containers:
  - name: dta-generator
    image: flairbi/flair-data-generator:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: RECORDS
        value: "100000"
      - name: FREQUENCY
        value: "5.0"
      - name: CONNECTION_TYPE
        value: postgres
      - name: HOST
        value: 10.123.96.3
      - name: PORT
        value: "5432"
      - name: USERNAME
        value: postgres
      - name: PASSWORD
        value: admin
      - name: DATABASE
        value: logistics
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

